title: timber

markdown: kramdown

baseurl: /timber

github:
  repo: https://github.com/scalawag/timber
  branch: series/0.7
  path: src/jekyll

kramdown:
  syntax_highlighter: rouge

version: "0.7.0-SNAPSHOT"
