language: scala

before_install:
 - rvm install 2.3.0

install:
 - gem install jekyll -v 3.0.1

script: "sbt clean coverage test && sbt coverageAggregate"

scala:
 - 2.11.7

jdk:
 - oraclejdk8
 - oraclejdk7
 - openjdk7

after_success:
 - sbt coveralls
 - git config --global user.email "travis@scalawag.org"
 - git config --global user.name "Travis CI Builder"
 - git config --global push.default simple
 - git config --global credential.helper "store --file=/tmp/gitcredentials"
 - echo "https://${GH_TOKEN}@github.com" > /tmp/gitcredentials
 - sbt ghpagesPushSite

env:
  global:
  - secure: "a6gYNmtF1ZOzj9dka89jYZCsadtXuLSXDCU7QECBe+pksdv07ZZCNPZwrRbS/7X2WMbqjzAviChsqyiIwS+FhMngnO3iSHCKcemUPjLcySu6jwCsGRXVX+cqQe0ngm+I5Rf1jQ9GzuPv/Ne+4obyOMwmjIW3fObi1FYvVOi96agKmK/xGdtMEontNa3eBo9YyPvniakXEkTza1tATs/0HTXPYu801B3S1QDVm530CJlGXRooPo7MS3fXxFkiNzvNL8FO5MyS8gCz+f+h4zITFkxJLpBVxN5ZqkPo2k/nCmSC8mRuLPjC4mwGUhw+1VEaGg23Zebr6mF9w624nrYN9UPJBXZjJf36uARFpBlygwVeo3qn0D/nK2ZkDGiDyfc8LvjNjcBVwe5ScEZDhUGJeTt86bN8YJUE2d5A5Gn2nGGz4uICOL6YW3S87GtNemLSHHsHrQBIWngAEo5EPABobBTgqOfIOzIZkTOmfux0Es/fCHakQEkzUeinjo2Od1N77jA8XyGpJJZ2MEFLKI1h+E34KNW40h5xwg8iOYCZ6eFMJfUG9WxE9CRi4j/VhY7yMDFATlyzX38oyQtGCjoBsMGmzR2hS4B+rEk82yDvmCKXUzRhxODbzayqNlRKIOZoEZPYylK1EILgn9bVlqhKLyDB9MZiyu7Mk8uCv/hdJ+U="

