language: scala

install:
 - gem install jekyll -v 3.0.1

script: "sbt clean coverage test && sbt coverageAggregate"

scala:
 - 2.11.7

jdk:
 - oraclejdk8
 - oraclejdk7
 - openjdk7

after_success:
 - sbt coveralls
 - sbt ghpagesPushSite

env:
  global:
  - secure: "Dy6c7Yh6kGz9Lm89BPNnivcc09PgmXnpcGBX8Ab4kYdJOKabfIw6KAhxklOeXDPl/UrNUQdVbTI0NEC9U5s1ygqDZ62998kUMFMhPYNjJzIpbIwEP+wH6B/stVPxZ8t0S7uK3Fg9G6G2lV6TX9SHfHjwY2han3NaUzz3WIR4BRvxe6GtDplCZ6r5pv1B+ehLAZ3t8acTyR4RcWEN0AMVm7MMqLCzY+s4hrbywuPCQ/MVDIrMOGIdfq9t7stsj6cGWHIJVLSnLelA8Xz0FS9iEqj9NNizlR4rKqH6qX5/h/tFor9PLC47G4Rg2HBmKjYdA8FCvnphytrLk5HOZGfi18qxrxbVR3V24EvUvGCrSPBH7+eYey2dDwPtI0wtgO/NSa5CbVpZNI6vARreJrveCOikZJOL/jMiQZSEeacSxvBDntK8UAjJ40us0fkivkjVq2U4iO3luH6iSHBZc+ITWJuLP4QFYv/YWpk5v5L34j2XiLveFxren5J+lgX2tFH7HhBaUXdVBWJJ+lGfej59OpBV3rkC6QzklnXufCvzmq/I4MpnksMNCqg4vpcYu+7+82YiTb957PLMXxqKy5y4QHPCCSK5uIiFYFPmA9J/S245rzk5iRM806IKCNumkU4dM8SSGYo5WTbJaQgnjUBsFik5GhqGoAvQoNzy4KN9PDk="

