language: scala

before_install:
 - rvm install 2.3.0

install:
 - gem install jekyll -v 3.0.1

script: "sbt clean coverage test && sbt coverageAggregate"

scala:
 - 2.11.7

jdk:
 - oraclejdk8
 - oraclejdk7
 - openjdk7

after_success:
 - sbt coveralls
 - git config credential.helper "store --file=.git/credentials"
 - echo "https://${GH_TOKEN}:@github.com" > .git/credentials
 - sbt ghpagesPushSite

env:
  global:
  - secure: "TXaWoU/GLF9Kj2azlou6HHRLHJvR9oAhwudbNZ2uFRfc6F3H0zlGKnJw3hVMMXF+DQEYmBjsBvejkGTVqBCElsGVmYvbHt6yPMDFvTIInCn9uwJ/kuOU4m+Pss0IAYKDbAxVsQYkT8JH6ApClAZmbhIjMa1ju95eSqfkHkRCkIuaRJfEc/i3gVhRjLcBzquKdCUDfuNNg/syX7KTZTHbjVCyrKw6kwI2nHlSxHzfoDEdRPmEzlOrkrMXb5mBOoL2conyLTPBsitqdxJpWcoWgmE8jdcQ3rmvr5s6F5Z4Jlc544AC39NhheGQzhC/mscwVoYIICl2pMjWRyyn052bORHVclZvsQpFkUmXVleYP7kjvUzCDcv4/dKqafhU5qShRED0pK3jPaay+ySEqL9WQsrWtmBDiOHhOhNAxy5tUxdAIgvcOL1bpr6ctNX5u+obUM09LA3vi53TAv3PUmBUhglHjz9KOXg394y1DJdYnOJCZF80Dj8DNRq9DSLEIvrdVIj6mk6hkQaCtOyjmJfLCB3rk7E4JHifRj+06ykSLGZhR6kmeuIET2Q/t64ILILarQx/F79cGXbTD62OSSHCyNiNhfjwQjqK3dDFjKOEDIGT9VscpmpOAOPu4OlR4WqYCPqSLMEurMadnGGum4Gs9m28Oi0IPtAU4AAcgxBym8k="

