on:
  push:

jobs:
  artifacts:
    runs-on: ubuntu-latest
    env:
      PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
      SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
      SONATYPE_USER: ${{ secrets.SONATYPE_USER }}
    steps:
      - name: git checkout
        uses: actions/checkout@v2
      - name: coursier cache
        uses: coursier/cache-action@v5
      - name: install jdk 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: sbt test publishSigned
        run: sbt +test +publishSigned
      - name: sbt release
        if: startsWith(github.ref, 'refs/tags/')
        run: sbt sonatypeRelease
  documentation:
    runs-on: ubuntu-latest
    steps:
      - name: git checkout
        uses: actions/checkout@v2
      - name: gem cache
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - name: install jekyll
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6
          bundler-cache: true
      - name: sbt makeSite
        run: |
          export PATH="$PATH:$PWD/vendor/bundle/ruby/2.6.0/bin"
          export GEM_HOME="$PWD/vendor/bundle/ruby/2.6.0"
          sbt makeSite
      - name: publish gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target/site